@startuml

!theme toy
skinparam shadowing true
mainframe **sd** User Login

actor User
boundary "Halaman Login : View" as halamanLogin
control Controller as controller
entity "Tabel User : Model" as dataUser
boundary "Halaman Utama : View" as halamanUtama

User -> halamanLogin ++ : Masuk halaman login ()
activate User
User -> halamanLogin : Input username dan password ()

halamanLogin -> controller ++ : Request login ()
controller -> dataUser ++ : Get user ()
dataUser --> controller : validasi ()
deactivate dataUser
controller --> halamanLogin : Response validasi ()
deactivate controller
alt #lightgreen Valid Login
halamanLogin --> User : Login sukses ()
User -> halamanUtama : Masuk halaman login ()
else #pink Invalid Login
halamanLogin --> User : Login gagal ()
deactivate halamanLogin
end

@enduml
