@startuml

!theme toy
skinparam shadowing true
mainframe **sd** Registrasi Tipe
autonumber

actor "Admin / Karyawan" as user
boundary "Halaman Tambah Tipe" as tambahTipe
control Proses
entity "Tabel Tipe" as tabelTipe

activate user
user -> tambahTipe ++ : Klik tombol registrasi()
deactivate user
tambahTipe -> Proses ++ : Input ID tipe, Quantity tipe()
deactivate tambahTipe
Proses -> Proses : validasi input()

alt #lightgreen Valid input
Proses -> tabelTipe ++ : Insert data()
deactivate tabelTipe
else #pink Invalid input

Proses --> tambahTipe ++ : Invalid character ()

deactivate Proses
deactivate tambahTipe
deactivate tabelTipe
end

@enduml
