@startuml

hide circle
!theme plain

entity schedules_supply_subjig {
*id : VARCHAR(55) <<PK>>
--
*month : DATE
*created_at : TIMESTAMP
--
type_id : VARCHAR(55) <<FK>>
}

entity schedule_weeks {
* id : VARCHAR(55) <<PK>>
--
*tanggal : DATE
*is_implemented : TINYINT
*created_at : TIMESTAMP
--
*schedule_supply_subjig_id : VARCHAR(55) <<FK>>
}

entity supplies {
*id : VARCHAR(55) <<PK>>
--
*target_set : INT
--
*schedule_week_id : VARCHAR(55) <<FK>>
*type_id : VARCHAR(11) <<FK>>
}

entity types {
*id : VARCHAR(11) <<PK>>
--
*type_qty : INT
*created_at : TIMESTAMP
}

entity subjigs {
*id : VARCHAR(55) <<PK>>
--
*order_number : INT
*subjig_name : VARCHAR(55)
*subjig_qty : INT
*created_at : TIMESTAMP
updated_at : TIMESTAMP
--
*type_id : VARCHAR(55) <<FK>>
}

entity supply_lines {
*id : INT <<PK>>
--
*jumlah_line_a : INT
*jumlah_line_b : INT
*jumlah_line_c : INT
*total : INT
*target_set : INT
--
*supply_id : VARCHAR(55) <<FK>>
*subjig_id : VARCHAR(55) <<FK>>
}

schedules_supply_subjig}|---||types
schedules_supply_subjig||---|{schedule_weeks
supplies||---||schedule_weeks
subjigs}|---||types
supply_lines}|---||subjigs
supply_lines}|---||supplies
supplies}|---||types
@enduml