@startuml

left to right direction

actor Database as mysql
actor BrowserSession as session

actor Admin as admin
actor Leader as leader
actor Karyawan as karyawan

rectangle "Schedule Supply Application" {

package Login {
admin ---- (login)
leader ---- (login)
karyawan ---- (login)
login <.. (Display Error) : <<extend>>
login ..> (User Validation) : <<include>>
}

package User {
(Kelola User) as userManagement
(Add User) as addUser
(Display User) as displayUser
(Update User) as updateUser
(Delete User) as deleteUser
admin --- userManagement
userManagement <|-- addUser
userManagement <|-- displayUser
userManagement <|-- updateUser
userManagement <|-- deleteUser
}

package Type {
(Kelola Type) as listItem
(Registrasi Type) as regType
(Display Type) as displayType
(Update Type) as updateType
(Registrasi Item) as regItem
(Update Item) as updateItem
(Delete Item) as deleteItem
(Display Item) as displayItem
admin --- listItem
karyawan --- listItem
leader --- displayType
leader --- displayItem
listItem <|-- regType
listItem <|-- displayItem
listItem <|-- displayType
listItem <|-- updateType
listItem <|-- regItem
listItem <|-- updateItem
listItem <|-- deleteItem
}

package Schedule {
(Kelola Schedule) as schedule
(Buat Schedule) as createSchedule
(Display Schedule) as displaySchedule
(Delete Schedule) as deleteSchedule
admin --- schedule
schedule <|-- createSchedule
schedule <|-- displaySchedule
schedule <|-- deleteSchedule
}


(User Validation) ..> mysql : <<include>>
login <.. session : <<extend>>
userManagement ..> mysql : <<include>>
listItem ..> mysql : <<include>>
schedule ...> mysql : <<include>>

}


@enduml
