@startuml
!theme toy
skinparam shadowing true
skinparam linetype ortho
mainframe uc Hak Akses Admin
left to right direction

(Login)
:Admin:

(Dapat Unduh Data Supply Hanger) as downloadData

(Dapat Mengatur Data Pengguna) as manageUser
(Dapat Menambah Pengguna) as addUser
(Ubah Nama) as updateName
(Ubah Password) as updatePassword
(Ubah Hak Akses) as updatePermission

(Dapat Kelola Type) as manageType
(Registrasi Type Baru) as addType
(Ubah Type) as updateType

(Kelola Hanger) as manageHanger
(Registrasi Hanger) as registerHanger
(Ubah Hanger) as updateHanger
(Hapus Hanger) as deleteHanger

(Input Jadwal Supply) as addSchedule
(Hapus Jadwal Supply) as deleteSchedule

(Login) <.. downloadData : <<include>>

(Login) <.. addUser : <<include>>

(Login) <.. manageUser : <<include>>
manageUser <|-- updateName : <<extend>>
manageUser <|-- updatePassword : <<extend>>
manageUser <|-- updatePermission : <<extend>>

(Login) <.. manageType : <<include>>
manageType <|-- addType : <<extend>>
manageType <|-- updateType : <<extend>>

manageType ..> manageHanger : <<include>>
manageHanger <|-- registerHanger : <<extend>>
manageHanger <|-- deleteHanger : <extend>
manageHanger <|-- updateHanger : <extend>

(Login) <.. (Dapat Mencari Laporan) : <<include>>
(Dapat Mencari Laporan) ..> (Input Tahun dan Bulan) : <<include>>

(Login) <.. addSchedule : <<include>>
(Input Tanggal) .u.> addSchedule : <<include>>

(Login) <.. deleteSchedule : <<include>>

Admin - addUser
Admin --- manageUser
Admin --- manageType
Admin --- downloadData
Admin --- addSchedule
Admin --- deleteSchedule
Admin --- (Dapat Mencari Laporan)


newpage
!theme toy
skinparam shadowing true
skinparam linetype dash
mainframe uc Hak Akses Karyawan
left to right direction

(Login)
:Karyawan:

(Dapat Unduh Data Supply Hanger) as downloadData

(Dapat Kelola Type) as manageType
(Registrasi Type Baru) as addType
(Ubah Type) as updateType

(Kelola Hanger) as manageHanger
(Registrasi Hanger) as registerHanger
(Ubah Hanger) as updateHanger
(Hapus Hanger) as deleteHanger

(Membuat Laporan Supply) as createSupply
(Input Jumlah Target) as targetSet
(Input Jumlah Hanger Line A) as lineA
(Input Jumlah Hanger Line B) as lineB
(Input Jumlah Hanger Line C) as lineC

(Login) <... downloadData : <<include>>

(Login) <.. manageType : <<include>>
manageType <|-- addType : <<extend>>
manageType <|-- updateType : <<extend>>

manageType ..> manageHanger : <<include>>
manageHanger <|-- registerHanger : <<extend>>
manageHanger <|-- deleteHanger : <extend>
manageHanger <|-- updateHanger : <extend>

(Login) <.. createSupply : <<include>>
createSupply ..> targetSet : <<include>>
createSupply ..> lineA : <<include>>
createSupply ..> lineB : <<include>>
createSupply ..> lineC : <<include>>

(Login) <.. (Dapat Mengubah Laporan) : <<include>>
(Login) <.. (Dapat Mencari Laporan) : <<include>>
(Dapat Mencari Laporan) ..> (Input Tahun dan Bulan) : <<include>>

Karyawan --- manageType
Karyawan --- downloadData
Karyawan --- createSupply
Karyawan -- (Dapat Mengubah Laporan)
Karyawan --- (Dapat Unduh Laporan)
Karyawan --- (Dapat Mencari Laporan)


newpage
!theme toy
skinparam shadowing true
mainframe uc Hak Akses Atasan
left to right direction
skinparam linetype ortho
(Login)
:Atasan:

(Dapat Unduh Data Supply Hanger) as downloadData
(Dapat Melihat Daftar Type) as listItem

(Login) <.. listItem : <<include>>
(Login) <.. downloadData : <<include>>
(Login) <.u. (Dapat Mencari Laporan) : <<include>>
(Dapat Mencari Laporan) .r.> (Input Tahun dan Bulan) : <<include>>

Atasan -- downloadData
Atasan -- listItem
Atasan -- (Dapat Mencari Laporan)


@enduml
